# Generated by Django 2.1.4 on 2019-01-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailstreamforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainWhiteListSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_white_list', models.TextField(blank=True, help_text='Allowed email domains', verbose_name='Domain White List')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Email White list',
            },
        ),
    ]
